### ISSUE TITLE
(feat): disable secrets mounting with config.insecure=true flag

### ISSUE THREAD

**Issue by lukasmrtvy** [pomerium/pomerium-helm#105]
Hello,
`--set config.insecure=true ` flag should disable also https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/templates/authenticate-deployment.yaml#L125-L143 tls secrets mounting, its not possible to start deployment with `--set config.insecure=true` flag.

Thanks

**Comment by travisgroth** [comment]
HI - interesting.  I'm guessing that the current users allow the cert generation to proceed, so there are still secrets to mount.  If you wanted to make a PR, we'd be happy to improve this.

**Comment by lukasmrtvy** [comment]
By the way, pomerium helm chart with `--set config.insecure=true` and `--set config.generateTLS=true` is broken and deployment will not start.

**Comment by Vad1mo** [comment]
@lukasmrtvy did you try helm chart version 9.1.0?  or 9.0.0?

**Comment by travisgroth** [comment]
Closed by #116
