### ISSUE TITLE
README for `config.policy` is inaccurate

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium-helm#138]
`config.policy` does not require a base64 encoded value.

**Comment by LilaNKM** [comment]
Hello :) 
@travisgroth 
Can you give me an exemple How to fill it ? Even without base64 I've got some difficulty

**Comment by travisgroth** [comment]
@LilaNKM it should directly contain a policy block from our standard yaml config format:

https://www.pomerium.com/reference/#policy

**Comment by LilaNKM** [comment]
Thanks it's work :)
