### ISSUE TITLE
Maitain only one version of this chart and publish it on hub.helm.sh

### ISSUE THREAD

**Issue by victornoel** [pomerium/pomerium-helm#15]
From what I understood, the stable repo chart from helm is going to disappear.

It would make sense to start deploying the present repo somewhere (I'm not sure what are the options for this) and publish it on hub.helm.sh.

**Comment by travisgroth** [comment]
Hey Victor.  Yes, they are deprecating helm/stable, so we will need to take next steps.  I don't think there's an official timeline yet so we're not in a big rush.

In the mean time, the visibility of being in helm/stable is worth the occasional headache so I'm happy to keep them in sync while helm hub picks up adoption.  The CI pipeline in helm/stable is actually nice to leverage as well.  We'll need to port some of that over.

I think the next obvious action is make sure we're publishing into hub so there's no gap in visibility.  After that, we can close any CI gaps and wait for hard shutdown of helm/stable.

**Comment by desimone** [comment]
With v3, I think we may want to take another look at maintaining just this repository. So far as I can tell, there are no longer any discovery advantages to using the official repository vs our own. 

```sh
$helm search hub pomerium

URL                                               	CHART VERSION	APP VERSION	DESCRIPTION
https://hub.helm.sh/charts/banzaicloud-stable/p...	1.0.6        	0.0.3      	Pomerium is an identity-aware access proxy.
https://hub.helm.sh/charts/stable/pomerium        	4.1.4        	0.5.2      	Pomerium is an identity-aware access proxy.
```

The main benefit  would be the prowl bot tester, I think. 

It looks like we could do most (if not all?) directly from github using gh-pages and actions.

- https://github.com/marketplace/actions/helm-chart-testing (by helm project)
- https://github.com/marketplace/actions/helm-chart-releaser (by helm project)
- https://helm.sh/docs/topics/chart_repository/
- https://github.com/marketplace/actions/helm-push-action
- https://github.com/marketplace/actions/github-action-for-helm-templates-validation

Thoughts @victornoel / @travisgroth ?

**Comment by travisgroth** [comment]
The chart testing and "kind" actions are the key CI pieces I'd been putting off, assuming we'd have to create it.  In hindsight, that was foolish 😄 

With those community sourced, I think we indeed plan the move.

**Comment by travisgroth** [comment]
https://github.com/pomerium/pomerium-helm/pull/42
https://github.com/pomerium/pomerium-helm/pull/44

A little more to do, but we're on the way to closing this.

**Comment by desimone** [comment]
@travisgroth I think we are good to go now ? btw, I tested this with helm 3 and everything works as expected 👍

**Comment by desimone** [comment]
Done!
