### ISSUE TITLE
Secret generation issues with ArgoCD

### ISSUE THREAD

**Issue by spencergilbert** [pomerium/pomerium-helm#155]
**Is your feature request related to a problem? Please describe.**

If a user is deploying the pomerium chart through [ArgoCD](https://argoproj.github.io/argo-cd/) the hooks that are used to generate TLS or signing key secrets are treated as if they are set to "forceGenerate" causing some downtime during any deploy. https://argoproj.github.io/argo-cd/user-guide/helm/#helm-hooks

**Describe the solution you'd like**

No clear solution, yet.

**Describe alternatives you've considered**
@travisgroth @desimone and I discussed a few workarounds in Slack including:

1. Allow users to annotate the generated secrets and annotate with: 
```yaml
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
```
They could then generate initially and then set `config.generate*` to false, with the annotations stopping ArgoCD from pruning the existing secrets.

2. Bring your own secrets, outside of this chart - either by creating the certs yourself or by allowing this chart to generate the resources, pull the resources out, and then deploy them separately.

**Comment by spencergilbert** [comment]
@travisgroth perhaps a good solution is being able to provide values for the TLS secrets as we currently can for the `proxy.signingKey`. Using SOPS makes that dead simple.

**Comment by victornoel** [comment]
@spencergilbert isn't that already possible, cf https://github.com/pomerium/pomerium-helm/tree/master/charts/pomerium#self-provisioned?

At least in the past I successfully provided my own tls secrets via sealed-secret for example, so with sops it should be similar :)

**Comment by spencergilbert** [comment]
More or less @victornoel, the signing key secret is maybe slightly easier since the chart can still create the secret for you and populate it from your values.

I'm planning on doing the currently supported sops+ build my own secret but it could be a way to support (unless we bring our own CA to cert manager)

**Comment by travisgroth** [comment]
🤔  I think passing the certs as values is possible but not documented:

https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/templates/tls-secrets.yaml#L156-L185

`[service].tls.cert`
`[service].tls.key`

We should add that to the README.  

I'd support adding in annotation support for the generated secrets if you wanted to open a pr @spencergilbert.

**Comment by spencergilbert** [comment]
It looks like we're also seeing https://github.com/pomerium/pomerium-helm/blob/master/charts/pomerium/templates/_helpers.tpl#L445-L446 these values regenerate when Argo syncs, causing all of the deployments to update due to the new hash for the static config
