### ISSUE TITLE
authenticate.redirectUrl config takes no effect

### ISSUE THREAD

**Issue by adamantal** [pomerium/pomerium-helm#211]
## What happened?
The following config takes no effect: `authenticate.redirectUrl`

## What did you expect to happen?
To have effect.

## Steps to reproduce
Deploy the chart with that config configured to anything.

## What's your environment like?

- Chart version: 22.0.0 + #209
- Container image: v0.14.7
- Kubernetes version: 1.20
- Cloud provider: EKS
- Other details: -

## What are your chart values?

This is the config I'm referring to.
```values.yaml
...
authenticate:
  ...
  redirectUrl: ""
  ...
...
```

## What are the contents of your config secret?
Not relevant

## What did you see in the logs?
Not relevant

## Additional context
I checked Pomerium's code and the redirect URL stems from the following formula: `proxy.authenticateServiceUrl` + `/oauth2/callback` see the code [here|https://github.com/pomerium/pomerium/blob/master/authenticate/handlers.go#L114]. The config is a bit confusing (though it would take effect), and has no use. It worth considering to remove it from `values.yaml`.

**Comment by travisgroth** [comment]
Thanks @adamantal.  This looks like it hasn't worked for a very long time.  I think you're right and we should just remove it at this point.
