### ISSUE TITLE
Support networking.k8s.io/v1 Ingress API 

### ISSUE THREAD

**Issue by sherifkayad** [pomerium/pomerium-helm#213]
**Is your feature request related to a problem? Please describe.**

For Kubernetes clusters >= 1.19 (e.g. now we are running 1.21) one would get a deprecation notice that the currently used Ingress API by Pomerium `networking.k8s.io/v1beta1` is deprecated and will be removed in k8s v1.22.

**Describe the solution you'd like**

I would like to see Pomerium support the newest stable version `networking.k8s.io/v1` for cluster versions >= 1.19. That also has an implication on the structure of the Ingress object (e.g. using `service.name` instead of `serviceName` or the need for the `pathType`, .. etc.) 

**Describe alternatives you've considered**

No real alternatives .. I mean starting k8s v1.22 the Pomerium Ingress as is won't work anymore.

**Explain any additional use-cases**

Nothing further.

**Additional context**

Nothing further. If that would be a fix on the level of the charts only, I am happy to submit a PR myself.

**Comment by travisgroth** [comment]
Hi @sherifkayad - you're right.  If you're up for making a PR, that would be welcome.  There is a helper template that I think just needs a tweak.  

I think this should be a minor bump, version wise.

**Comment by sherifkayad** [comment]
@travisgroth great stuff. Let me take a stab at that early next week and test the changes locally before submitting the PR.
