### ISSUE TITLE
config.yaml is not idempotent when using existing shared secret

### ISSUE THREAD

**Issue by fculpo** [pomerium/pomerium-helm#253]
When using an existing shared secret with for instance COOKIE_SECRET and SHARED_SECRET set in it, the helm chart keeps remdomizing these values in the config.yaml.

Each apply with exactly the same values hence changes the config.yaml and is not idempotent.

I believe those lines are at fault
https://github.com/pomerium/pomerium-helm/blob/708f64ced7dbb1b398c6a8ced8a70035938830e7/charts/pomerium/templates/_helpers.tpl#L490

We should not set these when using an existing shared secret.

**Comment by travisgroth** [comment]
Hi @fculpo,

You're right.  I think this was intended to be removed in https://github.com/pomerium/pomerium-helm/pull/220 but got lost in the changes.
