### ISSUE TITLE
Redis auth secret created even when redis.auth.existingSecret is set

### ISSUE THREAD

**Issue by albertrdixon** [pomerium/pomerium-helm#259]
## What happened?

I deployed the helm chart with `redis.auth.existingSecret` set to an existing secret in the cluster. However, the chart generated and deployed a kubernetes `Secret` object anyway

## What did you expect to happen?

The chart not to deploy a `Secret` and use the `exsistingSecret` I specified

## Steps to reproduce

1. Create an existing `Secret` in the cluster
2. Install the chart with `redis.auth.existingSecret=<existing secret name>`
3. The chart creates a secret with that name anyway

## What's your environment like?

- Chart version: `28.0.2`
- Container image:  `0.16.2`
- Kubernetes version: `1.22`
- Cloud provider: `N/A` (local homelab cluster)
- Other details: I deploy all of the secrets using `SopsSecrets` so I expect to be able to disable secret generation globally in this chart

## What are your chart values?

> **NOTE**: only pasting the `redis` section as that is all that is. relevant here. I am using `existingSecret=...` and `generateSecret=false` everywhere else as well

```values.yaml
redis:
  enabled: true
  auth:
    existingSecret: pomerium-redis-credentials

  generateTLS: false
  tls:
    certificateSecret: pomerium-redis-tls
```

**Comment by travisgroth** [comment]
@albertrdixon FYI this had some unintended consequences that I missed.  In v30.0 the old syntax will be restored but you'll have a new flag to disable creating the secret.  See #269.
