### ISSUE TITLE
29.0.1 not in helm repository

### ISSUE THREAD

**Issue by abh** [pomerium/pomerium-helm#262]
The latest version on https://helm.pomerium.io is 29.0.0 (versus 29.0.1 in the release list here on GitHub).

https://artifacthub.io/packages/helm/pomerium/pomerium

**Comment by travisgroth** [comment]
https://github.com/pomerium/pomerium-helm/actions/runs/1795767211

**Comment by travisgroth** [comment]
Re-ran and I think we're good.  Thanks @abh
