### ISSUE TITLE
Return tls genSignedCert function back for proxy

### ISSUE THREAD

**Issue by emelyanovtv** [pomerium/pomerium-helm#263]
In this [specific commit](https://github.com/pomerium/pomerium-helm/commit/fc0be094c40f30d98e4e9eeb2acc57b761285618#diff-be42178717332999f701b7e9beb71aaf465b67173b972312dbc30b0f7af2d4c1L176) was removed `pomerium.proxy tls secret` generation. 

Is it possible return this feature with `genSignedCert ` for proxy back somehow, since I was trying to migrate to a new version of pomerium it's the only one problem that I don't know how to solve. Or there is some workaround or hack how I can fix it? 

Thanks in advance.

**Comment by emelyanovtv** [comment]
Probably I didn't investigate enough. But previous behavior was that proxy deployment was anticipating tls.crt at start from config file(proxy-tls was automatically generated), but after migration it's always failing because those file doesn't exists anymore(file not found).

**Comment by travisgroth** [comment]
We'd need more detail to determine what kind of issue you're running into.  The proxy should not fail to start on the current chart but you may need to follow [upgrade steps](https://github.com/pomerium/pomerium-helm/tree/master/charts/pomerium#upgrading) if you have an existing install.

For general help, please see [getting help](https://www.pomerium.com/docs/community/#get-help), but if you believe you've found a bug, feel free to follow the bug template so we can gather sufficient information.

**Comment by emelyanovtv** [comment]
The last silly question% why [this variable](https://github.com/pomerium/pomerium-helm/commit/fc0be094c40f30d98e4e9eeb2acc57b761285618#diff-be42178717332999f701b7e9beb71aaf465b67173b972312dbc30b0f7af2d4c1R156) was created, it's not used anywhere, and how it's related to proxy ?

**Comment by travisgroth** [comment]
> The last silly question: why [this variable](https://github.com/pomerium/pomerium-helm/commit/fc0be094c40f30d98e4e9eeb2acc57b761285618#diff-be42178717332999f701b7e9beb71aaf465b67173b972312dbc30b0f7af2d4c1R156) was created, it's not used anywhere, and how it's related to proxy ?

I'm not sure.  I suspect that was left in by mistake during the development of that refactor.  As you point out, I don't see it used anywhere.
