### ISSUE TITLE
Add ingressController.deployment.podAnnotations to documentation

### ISSUE THREAD

**Issue by HighWatersDev** [pomerium/pomerium-helm#295]
I needed to add an annotation to ingressController pod and I realized that the chart doc is missing its reference.

Chart documentation is missing `ingressController.deployment.podAnnotations` value referenced in [here](https://github.com/pomerium/pomerium-helm/blob/ad5d2314ac054fb8e3bc841c648738894a47b703/charts/pomerium/templates/ingress-controller-deployment.yaml#L37)

**Comment by alexfornuto** [comment]
Thanks for the heads up @HighWatersDev!
