### ISSUE TITLE
Supporting insecure_server 

### ISSUE THREAD

**Issue by mohsen0** [pomerium/pomerium-helm#31]
Hi

When the SSL offloading is done via the load balancer, helm deployment should not configure the service with a TLS certificate.

Are you open to idea of adding `Values.insecure_server: True/False` to support that in the helm chart?

**Comment by desimone** [comment]
Hi @mohsen0 !

I'm open to the idea of a configuration switch that allows insecure_mode, though I do think we should keep secure defaults (even where TLS termination is in place) and continue to encrypt inter-service communication for confidentiality.

/cc @travisgroth

**Comment by travisgroth** [comment]
Hi @mohsen0 - can you clarify the use case a bit?  If I'm following correctly, you're using TLS to your ingress but then don't want TLS to your pods.

My immediate thought is the TLS cert generation option (default to on) should make that a low/zero effort configuration.

What do you seek to gain or fix by turning off 'free' TLS to the pomerium service layer?

**Comment by mohsen0** [comment]
I am going to close this issue, In my case, I was sharing an nginx-ingress with the proxy and some other services and the backend protocol was http, I agree with your approach.

**Comment by bjoernw** [comment]
If im using istio and am already doing tls termination there can i just set the env var INSECURE_SERVER to not require tls from the istio sidecar to the pomerium pod?
