### ISSUE TITLE
wrong tax applied

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium-helm#343]
@desimone @wasaga 
Please correct me if I'm wrong, but I believe this didn't actually update the image tag deployed by the chart: https://github.com/pomerium/pomerium-helm/blob/4628cad97661c5ee59c7fdf7aee0f49217a862fe/charts/pomerium/values.yaml#L310

_Originally posted by @vixus0 in https://github.com/pomerium/pomerium-helm/issues/342#issuecomment-1568185803_

**Comment by wasaga** [comment]
fixed in https://github.com/pomerium/pomerium-helm/pull/344
