### ISSUE TITLE
service annotations

### ISSUE THREAD

**Issue by derrickburns** [pomerium/pomerium-helm#35]
Please modify your helm chart to allow distinct annotations for each service and deployment.

There are several use cases where being able to provide different annotations is useful, mainly having to do with secrets:

- reloader
- gloo gateway

**Comment by desimone** [comment]
Hi @derrickburns ,

Could you elaborate / link to some similar configurations so I can get a sense of what you had in mind?

Thanks!

**Comment by derrickburns** [comment]
Ah.  Ok.

Reloader is a service that restart pods in a deployment when a secret or configmap changes.  You configure reloader by adding annotations to a deployment.  I would like to automate the restart of pomerium deployments if the secrets or configmaps they depend on change.  Right now, you have different secrets for each deployment.  Hence, we need different annotations.

Similarly, the gloo gateway allows one to configure "upstreams" as requiring TLS.  This can be done my a gloo specific CRD or via an annotation on a service.  Again, if we use different TLS secrets for the different pomerium services, we need different annotations.

**Comment by desimone** [comment]
@derrickburns I think this makes sense. Would you be able to take on the PR? Thanks!

**Comment by travisgroth** [comment]
Closed by #38
