### ISSUE TITLE
Installation help

### ISSUE THREAD

**Issue by zshan52** [pomerium/pomerium-helm#63]
Hello,
I'm a student at Carnegie Mellon University. I'm trying to use pomerium to model zero-trust behavior but I am finding it difficult to follow the instructions. Is there a set of instructions I can use to install and run pomerium on my ubuntu machine?

**Comment by travisgroth** [comment]
This repo is the Kubernetes helm chart for pomerium.  The pomerium home page is https://pomerium.io.  It has documentation for a variety of setups.
