### ISSUE TITLE
Provide the possibility to store sensitive headers in secrets

### ISSUE THREAD

**Issue by abuzhynsky** [pomerium/pomerium-helm#67]
Hello.

`policy` allows to set custom headers via the `set_request_headers` section.
Headers can store sensitive data like bearer token for the Kubernetes dashboard.

The chart stores the policy in the `configmap`. k8s `secret` looks like a safer option.

It would be great if we could store `policy` or just sensitive bits of a `policy` in a `secret`.

I can a PR if you don't mind.

Thanks in advance.

**Comment by desimone** [comment]
@abuzhynsky  That's a good point. 

I think @travisgroth would probably have a more informed perspective on this but... I think ideally we'd have policy still be stored as a configmap and able to pull in fields from a secret. This should be possible because policy is just vanilla yaml. 

If you had an implementation in mind, I'd be very happy to review a PR. Thanks!

**Comment by abuzhynsky** [comment]
Being honest I don't have a better idea than just store the policy in a secret.
As I understand if we try to move the sensitive bits from the configmap to another location we can't do it with just Helm chart changes but have to change the application logic.
We could make a hack and merge the configmap and the secret in the entrypoint but it breaks the hot reloading and doesn't seem like a good option.
If you have better ideas - I'be happy to help with their implementation.

**Comment by travisgroth** [comment]
I'm not sure it's practical to split what helm sees as a single block of values into both ConfigMap and Secrets.  It isn't something I've seen.  More difficult would be how to re-consolidate the policy data from the two objects in pomerium's config parsing.  With the policy list being a single block, it doesn't sound very easy.  Refactoring the pomerium config format would probably be the solution here, though I wouldn't advocate for it to solve this particular problem.

I've definitely considered moving everything to a secret, as annoying as it is to deal with bas64 config as a user.  This might be the time to do so.

@abuzhynsky if you're game, I'm happy to work on this with you.  This will also need changes in the operator code to support.  I think they'd be relatively easy, though.

**Comment by abuzhynsky** [comment]
@travisgroth 
Just to be sure that I've got you right. :)
You are OK with the change the policy configmap to a secret in scope of this issue, right?
If so I'll send a PR in a few days (and one more in the `pomerium-operator` repository).

**Comment by travisgroth** [comment]
@abuzhynsky yes, but I think we shift the _entire_ config.yaml config map field into a secret field and mount that as a file.  

This would also allow us to shift the ENV vars we currently enumerate into the exposed config file as well.  Generally this will simplify the templating and logic in a few places and ensure all values are secure by default.

**Comment by abuzhynsky** [comment]
@travisgroth 
Yes, sure. I've formulated my intentions badly.
Sorry for the late answer - I was busy at work.
I'll make PRs this week.
