### ISSUE TITLE
allow setting pre-existing idp.serviceAccount

### ISSUE THREAD

**Issue by desimone** [pomerium/pomerium-helm#7]
@desimone this prevents the use of a service account when rolling my own secret containing the service account.

As a workaround, I can just set `authenticate.idp.serviceAccount` to `true` though. I'm not sure how to fix this so we may need to leave it like this but simply document the fact that if needed, it can be set to `true` when using `existingSecret`.

_Originally posted by @victornoel in https://github.com/pomerium/pomerium-helm/pull/5_

**Comment by travisgroth** [comment]
I'm fairly certain this is now supported.
