### ISSUE TITLE
Upgrade chart testing action

### ISSUE THREAD

**Issue by travisgroth** [pomerium/pomerium-helm#79]
https://github.com/helm/chart-testing-action/releases/tag/v1.0.0-rc.1

Brings in helm 3 support.

**Comment by victornoel** [comment]
@travisgroth quick question: does this mean helm2 won't be tested anymore or are both of them going to be tested?

**Comment by travisgroth** [comment]
I think we could do both for some period of time.  In general, I'm getting the impression that the community is running to v3 quickly so I'm not sure how important testing against v2 is.  Happy to try for both though.

**Comment by travisgroth** [comment]
@victornoel FYI, we were able to continue testing helm v2 though it is likely going to stop working at some point soon.  Even the `v1` metadata format isn't compatible with helm v3, leading to a bit of a hack to make v2 testing work.

**Comment by victornoel** [comment]
@travisgroth thx for the information, it's not going to be a problem IMHO, helm v3 is stable and anyway, I hope people don't just deploy charts in production without testing them first ;)
Btw I have stopped doing devops duties in my company so I don't follow so much what's happening with pomerium, hence my silence lately :)
