### ISSUE TITLE
policy and policyFile

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium-helm#86]
Its not clear how adding policy is working, especially if it should be base64 encodes. (hint it's not)

` Failed to render chart: exit status 1: Error: template: pomerium/templates/ingress.yaml:23:23: executing "pomerium/templates/ingress.yaml" at <.Values.config.policy>: range can't iterate over cG9saWN5OgogIC0gZ`

also `policyFile` is referenced in the docs but not implemented/used anywhere in the chart.

**Comment by travisgroth** [comment]
I believe these have both been addressed at this point.  Closing.
