### ISSUE TITLE
Insecure is still using port 443 and https naming convention 

### ISSUE THREAD

**Issue by Vad1mo** [pomerium/pomerium-helm#88]
#83 introduced insecure. 

Unfortunately it is incomplete. For example when using together with Traefik, then Traefik is [guessing](https://docs.traefik.io/routing/providers/kubernetes-ingress/#communication-between-traefik-and-pods) based on port number 443  and the port (name?) if the service should called plain or over tls. 

The setups with HTTP traffic over port 443 confuses Traefik as it assumes by port number & port name that the upstream service is secure which it isn't. 

If `insecure=true` change Ports from 443 to 80 and rename port from https to http.

**Comment by travisgroth** [comment]
@Vad1mo I've opened up #103 to try to address this.  Can you give it a shot and confirm it works as expected?
