### ISSUE TITLE
Authorize signing key missing

### ISSUE THREAD

**Issue by albertrdixon** [pomerium/pomerium-helm#98]
```
Chart: pomerium-8.5.1
AppVersion: 0.7.5
```

I'm using forwardauth with the nginx ingress controller and trying to have my backend service validate the JWT assertion after getting a request authenticated by pomerium. I am using a self generated EC key that we deploy alongside pomerium so I am sure the public key I am using is legit. 

Looking at the authorize deployment, I don't see `SIGNING_KEY` set. If I edit the deployment and add my signing key then all is well as expected.

https://github.com/pomerium/pomerium-helm/blob/a0c125fff3f506e66aa9665e4814e390abd52c9b/charts/pomerium/templates/authorize-deployment.yaml#L68-L86

**Comment by camerondavison** [comment]
it looks like it is also missing from authenticate which is causing the `/.well-known/pomerium/jwks.json` to be empty

**Comment by camerondavison** [comment]
@desimone you mentioned that i should ping you on this ticket. I ran into this problem when our team was trying to get the jwt assertion verification working. i think that you mentioned i should CC @travisgroth

**Comment by travisgroth** [comment]
Hi @camerondavison.  I've updated the PR for this https://github.com/pomerium/pomerium-helm/pull/101.  Could you try that out and confirm it works as expected?

Thanks!

**Comment by camerondavison** [comment]
I tested this PR LGTM.

**Comment by travisgroth** [comment]
Thanks @camerondavison.  Will take your feedback about option churn into account before merging.
